### ISSUE TITLE
4.2.3,4.2.4 Yaml 无法正确解析

### ISSUE THREAD

**Issue by zycgit** [zycgit/hasor#91]
```
dsPool:
  - ds.Config:
      - dsName: oracle
        dsConfigType: OracleConfig
        connConfigType: OracleConnConfig
      - dsName: mysql
        dsConfigType: MySqlConfig
        connConfigType: MySqlConnConfig
```
